name: markdown_quill
description: Convert between quill (delta) format and markdown
version: 1.0.0
repository: https://github.com/TarekkMA/markdown_quill

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  charcode: ^1.3.1
  collection: ^1.16.0
  flutter_quill: 6.0.1
  markdown: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  meta: ^1.7.0
  very_good_analysis: ^3.1.0